
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: myebs-sc
---
apiVersion: v1
kind: Pod
metadata:
  name: pvpod
spec:
  containers:
  - name: nginx1
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: myvol
    ports:
    - containerPort: 80
  volumes:
  - name: myvol
    persistentVolumeClaim:
      claimName: mypvc