apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: myebs-sc
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: myebs-sc
---
apiVersion: v1
kind: Pod
metadata:
  name: pvpod
spec:
  containers:
  - name: nginx1
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: myvol
    ports:
    - containerPort: 80
  volumes:
  - name: myvol
    persistentVolumeClaim:
      claimName: mypvc